### PR TITLE
fix: add namespace-level RBAC filtering for deployment listing (#99)

### LINKED ISSUE #99: Add namespace-level RBAC filtering for cross-namespace deployment listing
## Context

PR #90 introduced all-namespace listing for ModelDeployments — when no `namespace` query parameter is provided, `GET /api/deployments` calls `listClusterCustomObject` and returns deployments across all namespaces.

The backend uses its own service account credentials for K8s API calls, not the authenticated user's token. The auth middleware (TokenReview) validates identity only, so any authenticated user can see all deployments the service account has access to, regardless of their own namespace-level RBAC.

This is acceptable for the current experimental/dev usage, but needs to be addressed before multi-tenant or production use.

## Problem

In a multi-tenant cluster with namespace-based isolation, an authenticated user from `team-beta` calling `GET /api/deployments` (no namespace param) would see deployments from `team-alpha` and all other namespaces — leaking model names, GPU allocations, scaling configs, and deployment status.

## Proposed Solutions (pick one)

1. **SelfSubjectAccessReview per namespace** — after listing all deployments, filter results by checking if the user has `list` permission on ModelDeployments in each namespace
2. **User token impersonation** — pass the user's bearer token to the K8s API instead of using the service account, letting K8s RBAC naturally scope results
3. **Explicit opt-in** — default to configured namespace when no param is given; require `?namespace=_all` for cluster-wide listing (with RBAC check)

## Related

- PR #90 (introduced this behavior)
- `backend/src/routes/deployments.ts:79-83`
- `backend/src/services/kubernetes.ts:116-137`
- TODO comment: `// TODO (Rita): Ensure only namespaces the user has access to are listed`

## Additional cleanup

- Remove dead `resolvedNamespace` variable in `deployments.ts:79`
- Fix extra leading space on `listDeployments` method signature in `kubernetes.ts:116`

### PR DESCRIPTION
**Pull request by vivekk16**
Fixes #99 — the backend was using its own service account for all K8s API calls, so any authenticated user could see deployments from all namespaces regardless of their RBAC permissions.

- **User token passthrough**: Tenant-scoped operations (list/get/create/delete deployments, pods, logs) now use the authenticated user's bearer token. K8s RBAC enforces access naturally. Infrastructure operations (GPU capacity, CRD checks, TokenReview) continue using the service account.
- **SelfSubjectAccessReview fallback**: When `GET /api/deployments` is called without a namespace filter by a user without cluster-wide access, the backend discovers which namespaces the user can access via `SelfSubjectAccessReview` and queries each individually. Admins with a `ClusterRole` skip this — their cluster-wide list succeeds directly.

### Why two solutions were combined

In practice, Solution 2 (user token) alone left the no-namespace listing path returning empty for users with only namespaced Roles and K8s denies `listClusterCustomObject` without a `ClusterRole`. Combining  Solution 1 with 2 provides both security (user's token enforces RBAC at the K8s API level) and UX (no-namespace listing works for all users).

### CODE REVIEW

File: backend/src/routes/deployments.ts [hunk 1]
```diff
@@ -267,8 +270,9 @@ const deployments = new Hono()
       const { name } = c.req.valid('param');
       const { namespace } = c.req.valid('query');
       const resolvedNamespace = namespace || (await configService.getDefaultNamespace());
+      const userToken = c.get('token') as string | undefined;
 
-      const pods = await kubernetesService.getDeploymentPods(name, resolvedNamespace);
+      const pods = await kubernetesService.getDeploymentPods(name, resolvedNamespace, userToken);
```
Comment (sozercan) [inline backend/src/routes/deployments.ts]: Most deployment inspection routes in this PR now thread `userToken` into the Kubernetes layer, but the `/metrics` handler immediately below still calls `metricsService.getDeploymentMetrics(...)` without caller credentials. In auth-enabled multi-tenant clusters, that service fetches via cluster DNS or the backend kubeconfig/API proxy, so any authenticated user who knows a deployment name and namespace can still read another tenant's metrics without needing `get` access to the `ModelDeployment` itself.
